'use client';
import ProjectBrief from '@/components/ProjectBrief';
const universes = [
 {id:'marketing',number:'01',name:'FRAME MARKETING',image:'/projects/marketing/noir.jpg',alt:'Direção de moda e campanha — estudo visual',category:'ESTRATÉGIA + CRIAÇÃO',title:<>Sua marca.<br/>Outra presença.</>,intro:'Para lançar, reposicionar ou fazer sua marca ser reconhecida.',action:'Criar para minha marca',lead:'O que sua marca precisa dizer agora?',description:'Começamos pelo objetivo e pelo público. A linguagem, os formatos e os canais vêm dessa direção.',services:[['Estratégia & identidade','Posicionamento, conceito e linguagem visual.'],['Campanhas & conteúdo','Direção criativa, fotografia, filmes e peças de campanha.'],['Presença & distribuição','Planejamento de conteúdo, redes sociais e mídia paga.']],brief:'Traga seu desafio, público e canais. Construímos o escopo a partir disso.'},
 {id:'studio',number:'02',name:'FRAME STUDIO',image:'/projects/studio/event.jpg',alt:'Atmosfera de show — referência de cobertura',category:'FOTOGRAFIA + AUDIOVISUAL',title:<>Seu momento.<br/>Mais uma vez.</>,intro:'Para viver o evento agora. E sentir tudo de novo depois.',action:'Planejar meu evento',lead:'O que não pode ficar fora dessa história?',description:'Pessoas, atmosfera e momentos-chave orientam a cobertura. O resultado nasce da forma como você quer reviver e compartilhar o evento.',services:[['Fotografia de evento','Pessoas, ambiente, bastidores e momentos-chave.'],['Aftermovies & filmes','Captação, montagem, cor e ritmo para contar sua história.'],['Cortes & conteúdo social','Recortes e formatos verticais para compartilhar.']],brief:'Traga data, local e o que não pode faltar. Alinhamos formatos e prazos no planejamento.'}
];
export default function ServiceUniverses(){return <div className="service-posters">{universes.map(u=><article className={`service-poster offer-${u.id}`} key={u.id}>
 <img src={u.image} alt={u.alt} loading="lazy"/>
 <details className="offer-disclosure"><summary aria-label={`Explorar ${u.name}`}><span className="offer-label"><span>{u.number} / {u.name}</span><span className="offer-plus" aria-hidden="true">＋</span></span><span className="offer-front"><small>{u.category}</small><strong>{u.title}</strong><span>{u.intro}</span><span className="offer-explore">Conhecer possibilidades <span aria-hidden="true">↗</span></span></span></summary>
 <div className="offer-content"><span className="eyebrow">A DIREÇÃO DO SEU PROJETO</span><h3>{u.lead}</h3><p>{u.description}</p><dl>{u.services.map(([title,description],i)=><div key={title}><dt><span>0{i+1}</span>{title}</dt><dd>{description}</dd></div>)}</dl><p className="offer-note">{u.brief}</p></div></details>
 <div className="offer-action"><ProjectBrief initial={u.id} label={u.action}/><span>ESCOPO SOB MEDIDA</span></div>
 </article>)}</div>}
