import ServiceUniverses from '@/components/ServiceUniverses';
import ProjectBrief from '@/components/ProjectBrief';
import BrandLogo from '@/components/BrandLogo';
import {contact} from '@/data/config';
export default function EditorialSections(){return <>
 <section className="frame-manifesto" id="about"><span className="eyebrow">02 / A FRAME</span><h2 className="manifesto-title">A atenção passa.<br/><span>A sensação fica.</span></h2><div className="manifesto-bottom"><span>CRIAR. CONECTAR. PERMANECER.</span><p>Somos o encontro entre estratégia e olhar. Criamos para marcas que têm algo a dizer e para momentos que merecem ser revividos. Da primeira ideia ao último frame.</p></div></section>
 <section className="service-gallery" id="solutions"><div className="service-heading"><span className="eyebrow">03 / O QUE VAMOS CRIAR?</span><h2>Dois universos.<br/><em>O mesmo olhar.</em></h2><p>Encontre o ponto de partida<br/>para a sua próxima história.</p></div><ServiceUniverses/></section>
 <section className="process-section"><div className="section-meta"><span>04 / COMO ACONTECE</span><span>DA INTENÇÃO À IMAGEM.</span></div><div className="process-grid">{[{title:'A conversa.',text:'Sua marca: objetivo, público e canais. Seu evento: data, local e momentos que não podem faltar.'},{title:'A direção.',text:'Conceito, formatos, escopo e cronograma. Você sabe o que vamos criar antes de começar.'},{title:'O seu frame.',text:'Produção, seleção e finalização. Cada entrega acompanha o que faz sentido para o seu projeto.'}].map((step,i)=><article className="process-step" key={step.title}><span>0{i+1}</span><h3>{step.title}</h3><p>{step.text}</p></article>)}</div></section>
 <section className="contact-section closing-scene" id="contact"><img className="closing-image" src="/projects/studio/event.jpg" alt="" loading="lazy"/><div className="contact-top"><span>05 / A PRÓXIMA HISTÓRIA</span><span>PODE SER A SUA.</span></div><div className="contact-body"><h2 className="contact-heading">E se o próximo<br/><em>frame fosse seu?</em></h2><div className="contact-action"><p>Conte o que você imagina.<br/>Vamos encontrar o melhor enquadramento.</p><ProjectBrief label="Começar meu próximo frame"/>{contact.email&&<a className="direct-contact" href={`mailto:${contact.email}`}>Conversar por e-mail ↗</a>}<div className="contact-socials">{contact.instagram&&<a href={contact.instagram}>Instagram ↗</a>}{contact.whatsapp&&<a href={contact.whatsapp}>WhatsApp ↗</a>}</div></div></div><div className="cinema-signoff"><BrandLogo/><span>MARCA OU MOMENTO. FAÇA FICAR.</span><a href="#">Voltar ao início ↑</a></div></section>
 </>}
